### ISSUE TITLE
Feedback for Project Milestone 1

### ISSUE THREAD

**Issue by apednek** [airavata-courses/DSDummies#52]
Hello,

Me and my team were trying to review your project. But we came across few issues while setting-up the project.
1. As you mentioned in the wiki we tried cloning your repo but we got checkout error(Attached the screenshot below). So we went ahead and downloaded the zip to run the project.
2. The wiki description is not specific enough, for example you did not explicitly mention to download Anaconda to run the Flask-app in conda environment. But we went ahead and installed Anaconda. 
3. After installing Anaconda we ran the command for setting up the virtual environment. But we encountered an error(Attached screenshot below) because of which we couldn't proceed further.
4. Next we tried to follow the Docker steps which were mentioned. But "make" command is not working on my machine(Attached screenshot below). Is there a specific software which needs to be installed for it?

We are looking forward to hear from you in order to run your project successfully.

Git Checkout error
![image](https://user-images.githubusercontent.com/31995443/153318229-eac22623-8845-4c7d-a83b-842fd81b7dac.png)

Virtual environment error
![image](https://user-images.githubusercontent.com/31995443/153318471-46ffc039-85dd-4814-87f2-c3ef7847d219.png)

Make command error
![image](https://user-images.githubusercontent.com/31995443/153321560-e6632391-0729-43b1-8f7a-e0a4d464ee5d.png)

Best,
Team Ampersand

**Comment by Umangmsharma** [comment]
> Hello,
> 
> Me and my team were trying to review your project. But we came across few issues while setting-up the project.
> 
> 1. As you mentioned in the wiki we tried cloning your repo but we got checkout error(Attached the screenshot below). So we went ahead and downloaded the zip to run the project.
> 2. The wiki description is not specific enough, for example you did not explicitly mention to download Anaconda to run the Flask-app in conda environment. But we went ahead and installed Anaconda.
> 3. After installing Anaconda we ran the command for setting up the virtual environment. But we encountered an error(Attached screenshot below) because of which we couldn't proceed further.
> 4. Next we tried to follow the Docker steps which were mentioned. But "make" command is not working on my machine(Attached screenshot below). Is there a specific software which needs to be installed for it?
> 
> We are looking forward to hear from you in order to run your project successfully.
> 
> Git Checkout error ![image](https://user-images.githubusercontent.com/31995443/153318229-eac22623-8845-4c7d-a83b-842fd81b7dac.png)
> 
> Virtual environment error ![image](https://user-images.githubusercontent.com/31995443/153318471-46ffc039-85dd-4814-87f2-c3ef7847d219.png)
> 
> Make command error ![image](https://user-images.githubusercontent.com/31995443/153321560-e6632391-0729-43b1-8f7a-e0a4d464ee5d.png)
> 
> Best, Team Ampersand

Thanks for reviewing our project. If you noticed, we mentioned about the bug in our wiki. We have made some fixes for deploying our project on the docker and just run it using bash start.sh ,

would appreciate if you could take a clone again and just run the script (also updated in the wiki)  : 
bash start.sh

**Comment by apednek** [comment]
Hi Umang, 
Thanks for the quick response. I'm running your project on Windows hence I won't be able to execute the "bash" command.

**Comment by Umangmsharma** [comment]
Hi,

Are you even following the wiki completely ? If the script doesn't runs, you could follow the other commands, listed below. 
Please try to run properly once following the wiki.

**Comment by apednek** [comment]
I am very much following your wiki steps completely. I've spent my last 2 hours to execute all the commands as per your wiki page and I can see you have updated and deleted your wiki page several times in the past hour (You have also deleted the "local" steps now which I was initially following).

**Comment by Umangmsharma** [comment]
Thank you for your time. If you read our wiki initially, we had mentioned about a bug at the end of the wiki and it is still there. 
We had some issues deploying on the docker, we fixed that with issue https://github.com/airavata-courses/DSDummies/commit/137795265d6bb50217617d6650cf050fe1990faa. That helped us deploy our application completely on the docker. 

Secondly, we had to remove the manual installation steps anyways until our docker worked. As soon as that worked, I updated the wiki and didn't want to bother the TAs with the hassle of running so many commands. We were trying to simplify things which we did, your comment was in between those timelines.  

That being said, thank you for the time and effort your team has put in to execute our project. We appreciate it and have taken positive feedbacks and updated our wiki so that people could easily follow through. If you want to execute once , you can try.

Update wiki link : https://github.com/airavata-courses/DSDummies/wiki
