### ISSUE TITLE
[Improvement] Bash files doesn't work directly on machine 

### ISSUE THREAD

**Issue by impiyush83** [airavata-courses/DSDummies#53]
<img width="1260" alt="Screen Shot 2022-02-09 at 21 35 35" src="https://user-images.githubusercontent.com/20107021/153326440-95cc54f7-4cb7-433a-b770-15e7b8cb008e.png">

Suggestions: 

You could add the below line in your documentation.

Replace **#!/bin/bash/** to **#!/bin/bash** in your bash script
 
```
chmod 755 start.sh 
```

Thanks for the constructive feedback. We have made some changes to fix this and updated our wiki accordingly. Really appreciate it . Updated wiki : https://github.com/airavata-courses/DSDummies/wiki

Team Zilean 🦄

**Comment by Umangmsharma** [comment]
Closing this issue.

**Comment by Umangmsharma** [comment]
Closing this issue.
