### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by anbadrin** [airavata-courses/DSDummies#54]
I tried following the steps on the wiki page. I am unable to find any steps to checkout branches. It is unclear on how to change directory or run the bash command given on the wiki page. We need to pull and checkout the branch in order to run any commands. Could you please provide a little more detailed steps on how to go about that? 

Team Orion

**Comment by prernaa96** [comment]
Hello team Orion,

Thank you for reviewing our project.

You need to directly take the clone and navigate to DSDummies folder to run the steps (the script or individual commands)
You do not need any checkout branch as the default clone will take you to the main branch , which is where you need to run the code.

If there is still some confusion I can list down the steps and will update the wiki as well:

1) Create a new directory in your local machine
2) Open a terminal in the folder created above and run "git clone https://github.com/airavata-courses/DSDummies.git"
3) Type cd DSDummies (only folder in the directory)
4) Run the individual commands as listed or run the script.

Please let us know if you face any trouble.

**Comment by anbadrin** [comment]
Thank you so much for your detailed steps. I was able to reproduce the steps and get the project running. The UI looks amazing and the map animation is also done nicely. Overall the project looks brilliant.

**Comment by Umangmsharma** [comment]
Closing this issue.
