### ISSUE TITLE
Project Milestone 1 Feedback(Team Ampersand)

### ISSUE THREAD

**Issue by apednek** [airavata-courses/DSDummies#58]
Hi Team,

Thank you for fixing the errors which I mentioned in the previous issue(https://github.com/airavata-courses/DSDummies/issues/52). I will definitely try and setup the project some time in future.
On a side note, to run 'chmod' and 'make' command one requires a Linux based machine. I have a Windows machine hence was facing the issues.

Best,
Team Ampersand

**Comment by prernaa96** [comment]
Hello,

Yes, we will always take up the suggestions and improve on them now or in the future.. 

There are alternate Windows commands such as cacls. We will update these in our Wiki. 
Thank you for pointing that out.

Thanks

**Comment by apednek** [comment]
Hello Team,

So I did set up the project on another machine using the shell commands. 
The UI and the UX experience is seamless. The video factor is cherry on the cake. 
Very well done!

Best,
Team Ampersand

**Comment by Umangmsharma** [comment]
Closing this issue
